DATASET: 'CIEDataset'
DATA_PATH: '../data/cie'

POINT_CLOUD_RANGE: [-50, -50, -5, 50, 50, 5]  # Adjust based on CIE environment dimensions

DATA_PROCESSOR:
    - NAME: mask_points_and_boxes_outside_range
      REMOVE_OUTSIDE_BOXES: True

    - NAME: shuffle_points
      SHUFFLE_ENABLED: {
        'train': True,
        'test': False
      }

    - NAME: transform_points_to_voxels
      VOXEL_SIZE: [0.05, 0.05, 0.1]  # Smaller voxels for indoor environment
      MAX_POINTS_PER_VOXEL: 10
      MAX_NUMBER_OF_VOXELS: {
        'train': 80000,
        'test': 90000
      }

DATA_AUGMENTOR:
    DISABLE_AUG_LIST: ['placeholder']
    AUG_CONFIG_LIST:
        - NAME: gt_sampling
          USE_ROAD_PLANE: False  # Disable road plane for indoor scenes
          DB_INFO_PATH:
              - cie_dbinfos_train.pkl
          PREPARE: {
             filter_by_min_points: [
                 'Chair:5', 'Table:5', 'Monitor:5', 'Projection_Screen:5',
                 'Projector:5', 'TV:5', 'Computer:5', 'Misc:5'
             ],
          }

          SAMPLE_GROUPS: [
              'Chair:2', 'Table:2', 'Monitor:2', 'Projection_Screen:2',
              'Projector:2', 'TV:2', 'Computer:2', 'Misc:2'
          ]

          NUM_POINT_FEATURES: 4
          DATABASE_WITH_FAKELIDAR: False
          REMOVE_EXTRA_WIDTH: [0, 0, 0]
          LIMIT_WHOLE_SCENE: True

        - NAME: random_world_flip
          ALONG_AXIS_LIST: ['x', 'y']

        - NAME: random_world_rotation
          WORLD_ROT_ANGLE: [-0.3925, 0.3925]  # smaller rotation for indoor

        - NAME: random_world_scaling
          WORLD_SCALE_RANGE: [0.95, 1.05]  # smaller scaling for indoor


POINT_FEATURE_ENCODING: {
    encoding_type: absolute_coordinates_encoding,
    used_feature_list: ['x', 'y', 'z', 'intensity'],
    src_feature_list: ['x', 'y', 'z', 'intensity'],
}


DATA_CONFIG:
    _BASE_CONFIG_: cfgs/dataset_configs/kitti_dataset.yaml  # Start from KITTI configs
    MAX_SWEEPS: 1  # Single sweep for static scan
    POINT_CLOUD_RANGE: [-50, -50, -5, 50, 50, 5]  # Adjust based on CIE dimensions
    INFO_PATH: {
        'train': [cie_infos_train.pkl],
        'test': [cie_infos_test.pkl],
    }
    GET_ITEM_LIST: ["points"]
    FOV_POINTS_ONLY: False  # We want all points in the environment

CLASS_NAMES: ['Chair', 'Table', 'Monitor', 'Projection_Screen', 
              'Projector', 'TV', 'Computer', 'Misc']

